# The name of the workflow
name: Test


# This workflow will run on any push to the repository
on: push

jobs:
  test:
    # Similar to docker, we set up a virtual machine to run our tests
    runs-on: ubuntu-latest

    services:
      # This is a reference to a Docker container that we want to run
      # We're using the official Postgres image
      postgres:
        image: postgres:13.3
        # This is the port that the container exposes
        ports:
          - 5432:5432
        # These are environment variables that we want to set
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: airbnb-test

    steps:
      # Each step has a name, some code, and some options
      - name: Check out the code
        uses: actions/checkout@v3 # This is a reference to some code to run

      # This step installs the Python version we want
      - name: Set up Python 3.11.5
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5

      # This step installs pip, pipenv, and our dependencies
      - name: Install dependencies
        run: | # Note that there's no reference here — just commands to run
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
          pipenv run playwright install
        working-directory: ./web

      # Now we run our tests
      - name: Test with pytest
        run: |
          pipenv run pytest
        env:
          APP_ENV: test
        working-directory: ./web